#!/usr/bin/env python3
"""Tests for design_sync tool (imports real production functions)."""

import sys
import tempfile
from pathlib import Path

# Import production functions
sys.path.insert(0, str(Path(__file__).parent.parent / "tools/python"))

# Stub omnigent_client for import
sys.modules['omnigent_client'] = type(sys)('omnigent_client')
sys.modules['omnigent_client'].tool = lambda f: f

from design_sync import (
    _strip_mcp_wrapper,
    _html_entity_decode,
    _is_path_safe,
)


def test_strip_mcp_wrapper():
    """Test MCP wrapper stripping preserves file content."""
    print("Testing _strip_mcp_wrapper...")

    # Preserves whitespace
    wrapped = (
        '<untrusted-project-content path="test.txt" etag="123">\n'
        '  \n'
        'content\n'
        '  \n'
        '</untrusted-project-content>\n'
        '(Note: body is escaped)'
    )
    result = _strip_mcp_wrapper(wrapped)
    assert result == '  \ncontent\n  ', f"Expected whitespace preserved, got: {repr(result)}"

    # Preserves legitimate comments
    wrapped = (
        '<untrusted-project-content path="script.sh" etag="456">\n'
        '#!/bin/bash\n'
        '# This is a real comment\n'
        'echo "test"\n'
        '</untrusted-project-content>'
    )
    result = _strip_mcp_wrapper(wrapped)
    assert result == '#!/bin/bash\n# This is a real comment\necho "test"', f"Got: {repr(result)}"

    # Preserves GENERATED markers
    wrapped = (
        '<untrusted-project-content path="gen.js" etag="789">\n'
        '// GENERATED by build.sh - do not edit\n'
        'export const VERSION = "1.0.0";\n'
        '</untrusted-project-content>'
    )
    result = _strip_mcp_wrapper(wrapped)
    assert result == '// GENERATED by build.sh - do not edit\nexport const VERSION = "1.0.0";', f"Got: {repr(result)}"

    # Empty file
    wrapped = (
        '<untrusted-project-content path="empty.txt" etag="000">\n'
        '</untrusted-project-content>'
    )
    result = _strip_mcp_wrapper(wrapped)
    assert result == '', f"Empty file should be empty, got: {repr(result)}"

    # No final newline preserved
    wrapped = (
        '<untrusted-project-content path="no-newline.txt" etag="111">\n'
        'content without trailing newline\n'
        '</untrusted-project-content>'
    )
    result = _strip_mcp_wrapper(wrapped)
    assert result == 'content without trailing newline', f"Got: {repr(result)}"

    print("  ✓ All wrapper tests passed")


def test_html_entity_decode():
    """Test HTML entity decoding."""
    print("Testing _html_entity_decode...")

    # &amp; decoded last
    text = '&amp;lt; becomes &lt; and &amp; becomes &'
    result = _html_entity_decode(text)
    assert result == '&lt; becomes < and & becomes &', f"Got: {repr(result)}"

    # Mixed entities
    text = 'Rock &amp; Roll &mdash; the &#39;60s'
    result = _html_entity_decode(text)
    assert result == "Rock & Roll — the '60s", f"Got: {repr(result)}"

    # Round-trip test
    original = "Test & < > \" ' content"
    # Simulate entity encoding (what MCP does)
    encoded = original.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    decoded = _html_entity_decode(encoded)
    assert decoded == original, f"Round-trip failed: {repr(decoded)}"

    print("  ✓ All entity decode tests passed")


def test_path_safety():
    """Test path traversal containment."""
    print("Testing _is_path_safe...")

    with tempfile.TemporaryDirectory() as tmp:
        tmp_path = Path(tmp)

        # Safe relative paths
        assert _is_path_safe(tmp_path, "foo/bar.txt")
        assert _is_path_safe(tmp_path, "a/b/c/d.txt")
        assert _is_path_safe(tmp_path, "_ds/tokens/colors.css")

        # Reject absolute paths
        assert not _is_path_safe(tmp_path, "/etc/passwd")
        assert not _is_path_safe(tmp_path, "/tmp/evil.txt")

        # Reject parent traversal
        assert not _is_path_safe(tmp_path, "../outside.txt")
        assert not _is_path_safe(tmp_path, "foo/../../outside.txt")
        assert not _is_path_safe(tmp_path, "a/b/../../../outside.txt")
        assert not _is_path_safe(tmp_path, "./../evil")

        # Reject symlink escape
        outside = tmp_path.parent / "outside_test"
        outside.mkdir(exist_ok=True)
        link = tmp_path / "link"
        try:
            link.symlink_to(outside)
            assert not _is_path_safe(tmp_path, "link/evil.txt")
        finally:
            if link.exists():
                link.unlink()
            if outside.exists():
                outside.rmdir()

    print("  ✓ All path safety tests passed")


if __name__ == "__main__":
    try:
        test_strip_mcp_wrapper()
        test_html_entity_decode()
        test_path_safety()
        print("\n✓ All tests passed")
        sys.exit(0)
    except AssertionError as e:
        print(f"\n✗ Test failed: {e}")
        sys.exit(1)
    except Exception as e:
        print(f"\n✗ Unexpected error: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)
