#!/usr/bin/env python3
"""Standalone tests for design_sync helper functions (no omnigent_client import)."""

import sys
import tempfile
from pathlib import Path


# Inline copies of functions to test (avoiding omnigent_client import)
def _strip_mcp_wrapper(content: str) -> str:
    """Strip ONLY the MCP transport wrapper tags."""
    if content.startswith("<untrusted-project-content"):
        tag_end = content.find(">")
        if tag_end != -1:
            content = content[tag_end + 1 :]

    close_tag = "</untrusted-project-content>"
    close_pos = content.find(close_tag)
    if close_pos != -1:
        content = content[:close_pos]

    return content.strip("\n")


def _html_entity_decode(text: str) -> str:
    """Decode HTML entities, with &amp; decoded LAST."""
    import html

    text = text.replace("&amp;", "\x00AMPERSAND\x00")
    text = html.unescape(text)
    return text.replace("\x00AMPERSAND\x00", "&")


def _is_path_safe(base_dir: Path, target_path: str) -> bool:
    """Check if target_path is safe (stays within base_dir)."""
    try:
        base_abs = base_dir.resolve()
        target_abs = (base_dir / target_path).resolve()
        return target_abs.is_relative_to(base_abs)
    except (ValueError, OSError):
        return False


def test_strip_mcp_wrapper():
    """Test MCP wrapper stripping."""
    print("Testing _strip_mcp_wrapper...")

    # Preserves whitespace
    wrapped = (
        '<untrusted-project-content path="test.txt" etag="123">\n'
        "  \n"
        "content\n"
        "  \n"
        "</untrusted-project-content>\n"
        "(Note: body is escaped)"
    )
    result = _strip_mcp_wrapper(wrapped)
    assert result == "  \ncontent\n  ", f"Expected whitespace preserved, got: {result!r}"

    # Preserves legitimate comments
    wrapped = (
        '<untrusted-project-content path="script.sh" etag="456">\n'
        "#!/bin/bash\n"
        "# This is a real comment\n"
        'echo "test"\n'
        "</untrusted-project-content>"
    )
    result = _strip_mcp_wrapper(wrapped)
    assert result == '#!/bin/bash\n# This is a real comment\necho "test"'

    # Preserves GENERATED markers
    wrapped = (
        '<untrusted-project-content path="gen.js" etag="789">\n'
        "// GENERATED by build.sh - do not edit\n"
        'export const VERSION = "1.0.0";\n'
        "</untrusted-project-content>"
    )
    result = _strip_mcp_wrapper(wrapped)
    assert result == '// GENERATED by build.sh - do not edit\nexport const VERSION = "1.0.0";'

    # Empty file
    wrapped = (
        '<untrusted-project-content path="empty.txt" etag="000">\n</untrusted-project-content>'
    )
    result = _strip_mcp_wrapper(wrapped)
    assert result == ""

    print("  ✓ All wrapper tests passed")


def test_html_entity_decode():
    """Test HTML entity decoding."""
    print("Testing _html_entity_decode...")

    # &amp; decoded last
    text = "&amp;lt; becomes &lt; and &amp; becomes &"
    result = _html_entity_decode(text)
    assert result == "&lt; becomes < and & becomes &", f"Got: {result!r}"

    # Mixed entities
    text = "Rock &amp; Roll &mdash; the &#39;60s"
    result = _html_entity_decode(text)
    assert result == "Rock & Roll — the '60s", f"Got: {result!r}"

    print("  ✓ All entity decode tests passed")


def test_path_safety():
    """Test path traversal containment."""
    print("Testing _is_path_safe...")

    with tempfile.TemporaryDirectory() as tmp:
        tmp_path = Path(tmp)

        # Safe relative paths
        assert _is_path_safe(tmp_path, "foo/bar.txt")
        assert _is_path_safe(tmp_path, "a/b/c/d.txt")

        # Reject absolute paths
        assert not _is_path_safe(tmp_path, "/etc/passwd")
        assert not _is_path_safe(tmp_path, "/tmp/evil.txt")

        # Reject parent traversal
        assert not _is_path_safe(tmp_path, "../outside.txt")
        assert not _is_path_safe(tmp_path, "foo/../../outside.txt")
        assert not _is_path_safe(tmp_path, "a/b/../../../outside.txt")

        # Reject symlink escape
        outside = tmp_path.parent / "outside_test"
        outside.mkdir(exist_ok=True)
        link = tmp_path / "link"
        try:
            link.symlink_to(outside)
            assert not _is_path_safe(tmp_path, "link/evil.txt")
        finally:
            if link.exists():
                link.unlink()
            if outside.exists():
                outside.rmdir()

    print("  ✓ All path safety tests passed")


if __name__ == "__main__":
    try:
        test_strip_mcp_wrapper()
        test_html_entity_decode()
        test_path_safety()
        print("\n✓ All tests passed")
        sys.exit(0)
    except AssertionError as e:
        print(f"\n✗ Test failed: {e}")
        sys.exit(1)
    except Exception as e:  # noqa: BLE001 — top-level test harness reports any failure and exits nonzero
        print(f"\n✗ Unexpected error: {e}")
        import traceback

        traceback.print_exc()
        sys.exit(1)
